services:
  mongodb:
    image: mongo
    container_name: mongoDb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: hamza
      MONGO_INITDB_ROOT_PASSWORD: hamza


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hamza
      ME_CONFIG_MONGODB_ADMINPASSWORD: hamza
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network